map = [
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOO                                                 O",
    "O                                                                  O",
    "O                                                                  O",
    "O                                                                  O",
    "OO                                                                 O",
    "OO                                                                 O",
    "OOOOOOO                                                            O",
    "OOOO                                                               O",
    "OO                                                                 O",
    "OO                                                                OO",
    "OO                                                               OOO",
    "OO              OOOOOOOOO                                        OOO",
    "OO               OOOOOOO                                         OOO",
    "OO                 OOOO                                          OOO",
    "OO                                                               OOO",
    "OO                                hhhhhhhhhhhh                   OOO",
    "OOO                                                              OOO",
    "OOO                                                              OOO",
    "OOO                                                       OOOOOOOOOO",
    "OOO                                                        OOOOOOOOO",
    "OOO                                                            OOOOO",
    "OOO                                           OOOOOOOOOOOOOOOOOOOOOO",
    "OOO                                                 OOOOOOOOOOOOOOOO",
    "OOO                                               OOOOOOOOOOOOOOOOOO",
    "OOO                                 OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
]